name: hide_wls_icon
description: A simple command-line application for hiding the WSL icon from the Desktop.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

dependencies:
  ffi: ^2.1.2
  win32_registry: ^1.1.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
